import type { Metadata } from "next";
import NavBar from "@/app/ui/dashboard/navBar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={"fixed"}>
        <div className={"flex"}>
            <div className={"bg-white h-screen w-64 text-black align p-3 border-r-4 border-pink-500"}>
                <NavBar/>
            </div>
            {children}
        </div>
        </body>
        </html>
    );
}
